### ISSUE TITLE
ParserError: Expected pragma, import directive or contract/interface/library definition

### ISSUE THREAD

**Issue by oceanbaichuan** [System-Glitch/Solidity-IDE#19]
node_modules/ace-mode-solidity/test_browserify/data/Block.sol:2:1: ParserError: Expected pragma, import directive or contract/interface/library definition. {} ^

**Comment by System-Glitch** [comment]
Can you please provide more details? How did it happen, where is this error displayed?

**Comment by oceanbaichuan** [comment]
Open a new folder and it is done.

**Comment by System-Glitch** [comment]
Simply write the solidity version definition on top of your new source file, save, and it should go away.

```
pragma solidity >=0.4.22 <0.6.0;
```

Edit: now that I think about it, it looks like the compiler tries to compile node dependencies, which is not right and shouldn't happen. Are you using the last version of Solidity-IDE? Version 2.3.0 fixed that issue.

**Comment by oceanbaichuan** [comment]
I am using the last version of Solidity-IDE.Open a  folder that has ace-mode-solidity directory.

**Comment by System-Glitch** [comment]
Fixed in 74cb145.
Will be available in next release (v2.3.1)
